### ISSUE TITLE
Load Mixin files with TS-Loader

### ISSUE THREAD

**Issue by tomrav** [wix/stylable-integration#22]
Allows writing Mixin files in TypeScript instead of JavaScript.

**Comment by lbelinsk** [comment]
I have just stumbled this issue where I wanted to write a Mixin in ts.
Since it is not supported, I wrote the Mixin in `.js` but then it was ignored so I couldn't find it in the `dist` folder.

The tmp hack which I did for now:
https://github.com/wix-private/wix-ui-adi/pull/38

Whenever that will be supported, I would prefer to drop this local hack and change the Mixin to be written in `.ts`.

Thanks

**Comment by barak007** [comment]
In order to load ts files in stylable plugin you can add this in the `webpack.config.js`
```js
require("ts-node").register({ /* options */ });
```

**Comment by lbelinsk** [comment]
@barak007 can you elaborate please?
I am not sure what I need to do in order to write a mixin file in ts.
Maybe a link to some example?
